### ISSUE TITLE
can't disable regular icon request 

### ISSUE THREAD

**Issue by atanusanyal** [zixpo/candybar-sample#15]
Disable regular icon request but still showing on, have a look
![image](https://user-images.githubusercontent.com/7301670/88304469-ef454600-cd25-11ea-89b4-57cb72d59782.png)

**Comment by sarsamurmu** [comment]
Are you sure? It's not happening with me

**Comment by atanusanyal** [comment]
ok let me post, another sceenshot
![image](https://user-images.githubusercontent.com/7301670/88417657-ef197900-cdff-11ea-90c0-1932117c56ef.png)

**Comment by atanusanyal** [comment]
**OK LET ME POST, Another screenshot**
![image](https://user-images.githubusercontent.com/7301670/88417699-00fb1c00-ce00-11ea-84b9-d14da9efd09c.png)

**Comment by sarsamurmu** [comment]
Closing as it is already being tracked at the library repository
