### ISSUE TITLE
Google play store checking is not working

### ISSUE THREAD

**Issue by atanusanyal** [zixpo/candybar-sample#16]
After downloading from Google play store the first time opening perfectly checking the license and google play store checking perfectly, then the second time when the app is trying open its not opened it just crashed.

**Comment by sarsamurmu** [comment]
Try disabling `playstore_check`

**Comment by atanusanyal** [comment]
Yes, after disabling playstore_check its working but its not working license checking too.

**Comment by CatalystMonish** [comment]
In the liscense.java you are supported to add the randomn strings make sure you have added them correctly
