### ISSUE TITLE
adopt icon shape 

### ISSUE THREAD

**Issue by atanusanyal** [zixpo/candybar-sample#17]
where to find and change icon shape name 
![image](https://user-images.githubusercontent.com/7301670/97408340-f16d0100-1921-11eb-925d-8a0815c4224d.png)

**Comment by sarsamurmu** [comment]
You can't change that easily, it's hard-coded in the library.

**Comment by atanusanyal** [comment]
so i want to turn off this option
![image](https://user-images.githubusercontent.com/7301670/97409443-9dfbb280-1923-11eb-98d7-e3d9ead53982.png)

**Comment by sarsamurmu** [comment]
Set `includes_adaptive_icons` to `false` in `dashboard_configurations.xml`

**Comment by atanusanyal** [comment]
Thanks
