### ISSUE TITLE
Icons not applying with Poco launcher

### ISSUE THREAD

**Issue by mirrorkeydev** [zixpo/candybar-sample#18]
Steps to reproduce:
- Get Poco launcher (latest version)
- Get Appstract (version 4.0.0 or greater)
- Launch Poco and try to apply Appstract as icon pack

Expected behavior:
- The preview icons change to Appstract's version of the icons.
- All icons change to Appstract's version.

Actual behavior:
- The preview icons stay system default.
- All icons stay system default.

I've tested this using another popular icon pack, which worked fine with Poco; I also tested Lawnchair and Nova, and those were working great with Appstract, so I believe it is an issue with CandyBar. It's alright if CandyBar doesn't support Poco anymore (I'll just update my store listing), but in case this shouldn't be happening, I was wondering if you had any ideas.

This was brought to my attention by a user of Appstract, so it has been reproduced on at least two devices.

Edit: I just realized my list of launchers in my store listing doesn't even include Poco, so maybe it was never officially supported?

**Comment by sarsamurmu** [comment]
I think there's no special setup needed in the dashboard side to support POCO. One thing about POCO is that it reads `appfilter.xml` and `drawable.xml` from the `assets` directory, not from the `xml` directory like other launcher do. So to support POCO, don't forget to update `appfilter.xml` and `drawable.xml` in the `assets` directory. Maybe your XMLs in the `assets` directory are not in sync with the XMLs from the `xml` directory?

**Comment by mirrorkeydev** [comment]
That's definitely it, I accidentally left `assets` blank, whoops! Thanks so much for helping me figure out what the issue was :)
