### ISSUE TITLE
Application freezes

### ISSUE THREAD

**Issue by dhanu-saud** [zixpo/candybar-sample#2]
Hi,
Thanks for the update but after compiling and running on Redmi Note 7 Pro it freezes on splash screen.

Please confirm.

**Comment by OSHeden** [comment]
It should be fixed now.

**Comment by sarsamurmu** [comment]
@dhanu-saud if the problem still persist, can you give me the log? So I can look into the problem.

**Comment by dhanu-saud** [comment]
I updated to latest version and it is still has same issue on Redmi Note 8.

**Comment by dhanu-saud** [comment]
@sarsamurmu 
how can I find log report?
