### ISSUE TITLE
Request email issue

### ISSUE THREAD

**Issue by BUBULABS** [zixpo/candybar-sample#22]
There is an issue that when users try to request icons weather is premium or regular, the recipient email (developer email) email that shows is "your@email.com" instead of the developer email. For some reason that is happening, I could not figure that out. Thanks

**Comment by sarsamurmu** [comment]
Did you check `regular_request_email` in `dashboard_configurations.xml`? If there's no such field, add the field manually, like shown in this file - https://github.com/zixpo/candybar-sample/blob/main/app/src/main/res/values/dashboard_configurations.xml#L199

**Comment by BUBULABS** [comment]
Thank you. The field was missing, I appreciate  From: Sarsa MurmuSent: Sunday, January 24, 2021 2:31 PMTo: zixpo/candybar-sampleCc: BUBULABS; AuthorSubject: Re: [zixpo/candybar-sample] Request email issue (#22) Did you check regular_request_email in dashboard_configurations.xml? If there's no such field, add the field manually, like shown in this file - https://github.com/zixpo/candybar-sample/blob/main/app/src/main/res/values/dashboard_configurations.xml#L199—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by sarsamurmu** [comment]
Happy helping!
