### ISSUE TITLE
Migrating Google Play Billing Library to v3

### ISSUE THREAD

**Issue by BUBULABS** [zixpo/candybar-sample#24]
I am not sure if you are aware but just in case, is not really an issue but Google has launch a new version of the Billing Library since August. Apps that have older version of the library have until November 1, 2021. All updates to existing apps must use Billing Library version 3 or newer. Regarding to candybar also have an older version of the library. Maybe an update would be really great!. Anyways that is all. Take care.

There are a few links you may like to check out about the Billing Library v3

Info - https://android-developers.googleblog.com/2020/06/meet-google-play-billing-library.html

Implementation - https://developer.android.com/google/play/billing/migrate?authuser=1#java

**Comment by sarsamurmu** [comment]
I will try to update CandyBar with billing library v3 before August 1.

**Comment by sarsamurmu** [comment]
Billing library v3 is now available in CandyBar `v3.10.0`
