### ISSUE TITLE
Custom Button or

### ISSUE THREAD

**Issue by varlesh** [zixpo/candybar-sample#28]
Thx for your great library! I have one problem.
On my app i want added DONATE button, BUT without PlayStore link ID.
I mean, when you touch button > open list links (or buttons, like as `otherApps`) with supported methods. For example, paypal.me/*** or yoomoney.ru/to/*** and etc.
Yes, i know about `otherApps`, but this is not exactly what i wanted, because it's not app from PlayStore it's only links and they openned only on default browser and not possible open this link with preinstalled payment's apps.
Maybe it's possible create custom button with this function or another solution?
Thx

**Comment by sarsamurmu** [comment]
It's possible to implement this feature. But, currently, I'm busy, I will implement it whenever I get some time.

**Comment by sarsamurmu** [comment]
Update to `v3.13.2` and check this - https://github.com/zixpo/candybar-sample/wiki/Dashboard-configurations#donation-links
