### ISSUE TITLE
Icons tab empty when returning from search

### ISSUE THREAD

**Issue by leifniem** [zixpo/candybar-sample#29]
I just noticed after a search that going back with the top left arrow leaves the page empty, showing neither tabs nor icons below the title.

**Comment by Primokorn** [comment]
Which candybar version do you have? How many icons do you have?
No issue here with Candybar v3.16.2.

**Comment by walrus543** [comment]
I can reproduce the bug when `show_icon_name` is set to `false` (/res/valuesl/dashboard_configurations.xml).

**Comment by sarsamurmu** [comment]
This issue should be fixed in `v3.17.5`. Can you check again?

**Comment by OSHeden** [comment]
@sarsamurmu It's fixed for me.

**Comment by sarsamurmu** [comment]
I'm closing this. If the bug appears again, please reopen this issue.
