### ISSUE TITLE
Disable clock widget

### ISSUE THREAD

**Issue by dalight13** [zixpo/candybar-sample#3]
Any way to disable clock widget? Not really an issue I'm just looking for info and didn't know where to ask about it

Thanks for the pack it works amazing!

**Comment by sarsamurmu** [comment]
Just remove these lines to disable clock widget - https://github.com/zixpo/candybar-sample/blob/master/app/src/main/AndroidManifest.xml#L213-#L219

**Comment by dalight13** [comment]
Thank you you're the best!
