### ISSUE TITLE
Can't determine path to tools.jar

### ISSUE THREAD

**Issue by Technologx** [zixpo/candybar-sample#30]
Hi, I used this dashboard before and wanted to get into making icon packs again but when I try to sign the apk to see how the colors look that I chose I run into this issue and I've tried everything that I was finding on Google too.

`Cannot determine path to 'tools.jar' library for Android API 32 Platform (C:/Users/techn/AppData/Local/Android/Sdk)`

**Comment by sarsamurmu** [comment]
Did you set the `targetSdk` to `32`?

**Comment by Technologx** [comment]
It set it to that when I imported the project

**Comment by Technologx** [comment]
> Did you set the `targetSdk` to `32`?

How do I go about making Android Studio use 30 instead of 32?

**Comment by sarsamurmu** [comment]
Check these lines, make sure they are same in your case

https://github.com/zixpo/candybar-sample/blob/main/build.gradle#L22-L23

https://github.com/zixpo/candybar-sample/blob/main/app/build.gradle#L20-L21

**Comment by Technologx** [comment]
They are

**Comment by Technologx** [comment]
![image](https://user-images.githubusercontent.com/17693282/146878092-11d85297-4cc9-4064-b7a1-8f53b2e7b6ea.png)
![image](https://user-images.githubusercontent.com/17693282/146878193-6d5bc366-2481-44e1-b25f-90e0de5041bc.png)

**Comment by Technologx** [comment]
![image](https://user-images.githubusercontent.com/17693282/146981628-97384446-8a27-451f-8754-55eec4e204ec.png)
![image](https://user-images.githubusercontent.com/17693282/146981682-9315a2d9-ccaa-49be-8d97-1e4de113d7f9.png)
![image](https://user-images.githubusercontent.com/17693282/146981768-26d4113e-7d2e-4708-8cb4-8539c7e96352.png)
![image](https://user-images.githubusercontent.com/17693282/146981843-d798028c-1f13-4a93-915e-61167b344878.png)

Here's some more useful screenshots to help out.

**Comment by Technologx** [comment]
This can be closed, I updated to Android Studio Chipmunk and was able to select the build sdk. Artic Fox I wasn't able to.
