### ISSUE TITLE
Wiki: No such option as `New > Package`

### ISSUE THREAD

**Issue by JapanYoshi** [zixpo/candybar-sample#32]
I'm trying to follow the Wiki article for [Setting up the package](https://github.com/zixpo/candybar-sample/wiki/Setting-up-the-package), but I'm stuck on this step.

### 3. Changing package name
* If you're using Android View open the following directory `app/java`. If you're using Project View open `app/src/main/java`.
* Right-click on it. Choose `New > Package`

But when I right click on `app/java`, only the following options show up:

![image](https://user-images.githubusercontent.com/8707990/158087370-59889335-d123-4c37-8067-26ae120929fa.png)

Is "Resource bundle" the correct option? Or am I setting up the wrong verison of Android Studio?

---

Android Studio Chipmunk 2021.2.1 Beta 4
Build #AI-212.5712.43.2112.8233820, built on March 1, 2022

Runtime version: 11.0.12+7-b1504.28-7817840 amd64
VM: OpenJDK 64-Bit Server VM by Oracle Corporation

**Comment by sarsamurmu** [comment]
Did you sync gradle before doing that? AFAIK you have to gradle sync atleast one time before those options show up.

**Comment by JapanYoshi** [comment]
Gradle syncing fixed it, but the next step (cutting and pasting the contents of the old package) caused this:
![image](https://user-images.githubusercontent.com/8707990/158129683-72481761-64f2-4dbe-b4bd-2b291d9e0e8c.png)
