### ISSUE TITLE
Targeting R+ (version 30 and above) requires the resources.arsc of installed APKs to be stored uncompressed and aligned on a 4-byte boundary

### ISSUE THREAD

**Issue by KeithMarcusXIII** [zixpo/candybar-sample#34]
Hi, the app just refused to install no matter what I tried. Debugging fom Android Studio directly doesn't install. I also tried building unsigned apk and manually tried to `zipalign` the apk and also `apksign` the apk afterwards as well. But nothing works. It keeps complaining `failed to install signed.apk: Failure [-124: Failed parse during installPackageLI: Targeting R+ (version 30 and above) requires the resources.arsc of installed APKs to be stored uncompressed and aligned on a 4-byte boundary]`

**Comment by sarsamurmu** [comment]
I don't think it's related to CandyBar. Did you find a fix?
