### ISSUE TITLE
Multi-languages support for the string home_description

### ISSUE THREAD

**Issue by walrus543** [zixpo/candybar-sample#36]
Hello,
Could you please add a multi-languages support for the [home_description string](https://github.com/zixpo/candybar-sample/blob/b93b73b9189d2bd9b646ca750612a8d140fb5b00/app/src/main/res/values/dashboard_configurations.xml#L75).

[Java source](https://github.com/zixpo/candybar/blob/fd8af3ff32c11db545c4ee13c5ab4822f3a94dfa/library/src/main/java/candybar/lib/adapters/HomeAdapter.java#L215)

Thank you.

**Comment by Primokorn** [comment]
Already possible.
