### ISSUE TITLE
Add language

### ISSUE THREAD

**Issue by dhanu-saud** [zixpo/candybar-sample#4]
Is it possible to add my native language myself?

**Comment by sarsamurmu** [comment]
Is your language listed [here](https://support.crowdin.com/api/language-codes/)?

**Comment by dhanu-saud** [comment]
yes

**Comment by sarsamurmu** [comment]
Tell me language's name and I will set up the language on crowdin for you to translate.

**Comment by dhanu-saud** [comment]
it is ne-NP.

**Comment by sarsamurmu** [comment]
I have added the language. Just go to - https://crowdin.com/project/candybar and start translating :D

**Comment by dhanu-saud** [comment]
thanks bro..

**Comment by dhanu-saud** [comment]
done, can you plz let me know when it will be available?

**Comment by sarsamurmu** [comment]
It will be available on next update.
