### ISSUE TITLE
A new wiki page for adding icons and making them work

### ISSUE THREAD

**Issue by Donnnno** [zixpo/candybar-sample#48]
We've had a small discussion on Telegram about if the wiki should have a page for the actual icon pack basics. I thought that was pretty easy to set up, so I wrote some basics:

Let me know what you think!

--------------------------

# Adding icons and making them work

## Icons

- The recommended icon size is 256×256 px 
- Supported formats are PNG WebP and XML (Vector)
- place them in the `app/src/main/res/drawable-nodpi` folder

## Code

1. To make icons work in a launcher, you'll need to add some lines of code to the Appfilter: `app/src/main/values/appfilter.xml` & `app/src/main/res/xml/appfilter.xml`.
You can gather the info with an app like [Icon Request](https://play.google.com/store/apps/details?id=de.kaiserdragon.iconrequest), it should look like this:

```xml
<appfilter>

	<!-- CandyBar Dev -->
	<item component="ComponentInfo{com.candybar.dev/com.candybar.dev.activities.MainActivity}" drawable="candybar_dev"/>

</appfilter>
```

2. Paste all the info in both appfilter.xml files and check if the *drawable* name matches with your icon.
3. To preview the icons in your own icon pack, you'll need to add the names to the drawable.xml files too: `app/src/main/values/drawable.xml` & `app/src/main/res/xml/drawable.xml`.

```xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
<version>1</version>    
	
	<item drawable="candybar_dev" />

</resources>
```

**Comment by sarsamurmu** [comment]
I've given you the permission to edit the wiki. You can improve the page with better instructions :)

**Comment by sarsamurmu** [comment]
Also, I don't think it's required to edit the appfilter.xml and drawable.xml inside of `values` directory, only editing in `xml` directory will do

**Comment by Donnnno** [comment]
Thanks a lot!
I've experienced that some launchers use the value folder.
People can easily copy & paste the edited ones into the other folder.

**Comment by kshitijdeota** [comment]
To further clarify what @sarsamurmu is saying, editing the `appfilter.xml` and `drawable.xml` inside `values` directory is not required because it automatically gets copied over from `drawable` during build process.
