### ISSUE TITLE
Could not find com.github.chrisbanes:PhotoView:1.3.1

### ISSUE THREAD

**Issue by JkMulti** [zixpo/candybar-sample#50]
Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
Failed to transform PhotoView-1.3.1.aar (com.github.chrisbanes:PhotoView:1.3.1) to match attributes {artifactType=android-aar-metadata, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
> Could not find PhotoView-1.3.1.aar (com.github.chrisbanes:PhotoView:1.3.1).
Searched in the following locations:
https://jitpack.io/com/github/chrisbanes/PhotoView/1.3.1/PhotoView-1.3.1.aar
https://jitpack.io/com/github/chrisbanes/PhotoView/1.3.1/PhotoView-1.3.1.jar

**Comment by unmaskedfalesh** [comment]
latest version in 2.3.0

**Comment by sarsamurmu** [comment]
Use `v3.21.0`
