### ISSUE TITLE
Build Fail from Sample

### ISSUE THREAD

**Issue by ladle3000** [zixpo/candybar-sample#51]
Downloaded the newest sample and followed directions exactly and build fails due to deprecated gradle stuff:

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.
You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
For more on this, please refer to https://docs.gradle.org/8.9/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
BUILD FAILED in 3s
45 actionable tasks: 45 executed

**But when I try to do a build directly from the release package it works fine.**

I checked that the dashboard was up to date to 3.21.0 as well

**Comment by sarsamurmu** [comment]
I've released a new version - `v3.21.1`. Try using the new version.

**Comment by ladle3000** [comment]
> I've released a new version - `v3.21.1`. Try using the new version.

It's working now. I think the issue was actually an unescaped apostrophe

**Comment by ladle3000** [comment]
> I've released a new version - `v3.21.1`. Try using the new version.

It's working now. I think the issue was actually an unescaped apostrophe

> I've released a new version - `v3.21.1`. Try using the new version.

BTW, I've found some inconsistencies and language issues in the wiki. Could I contribute by helping with that? I'm not sure how to submit the changes.
