### ISSUE TITLE
Home screen icon dimension

### ISSUE THREAD

**Issue by pxflow** [zixpo/candybar-sample#8]
Please add an option to hide the "icon dimension" of the home screen.
Adaptive icons do not show the icon dimension; therefore, it makes no sense to leave an icon dimension on the home screen without information.

![Screenshot_2020-05-04-16-24-13-403](https://user-images.githubusercontent.com/39531151/81006932-b2546c00-8e26-11ea-88d5-8c8aefeb0fd0.jpg)

**Comment by sarsamurmu** [comment]
Actually, that's for showing a random icon everytime the app is opened. So I think that's not a problem.
